services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app

  mysql:
    image: mysql:8.4
    container_name: symfony_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: