# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

insert_coin:
    path: /insert_coin
    controller: App\Coin\Controllers\CoinsInsertController
    methods: [ 'POST' ]

return_coins:
    path: /return_coins
    controller: App\Coin\Controllers\CoinsGetBackController
    methods: [ 'GET' ]

service_machine:
    path: /service
    controller: App\MachineStatus\Controllers\ServiceMachineController
    methods: [ 'POST' ]
